"""Authentication plugin for Radicale."""

import hashlib
import hmac
import re
import time
from urllib.parse import parse_qs, quote_plus, urlsplit, urlunsplit

import requests

from radicale.auth.dovecot import Auth as DovecotAuth
from radicale.log import logger

from .modoboa_api import RightsClient

#: Timeout (in seconds) of introspection requests
INTROSPECTION_TIMEOUT = 10

#: Timeout (in seconds) of share link token checks
SHARE_TOKEN_TIMEOUT = 5

#: Prefix of the user names given to share link tokens. It must match
#: the one of radicale-modoboa-rights, and Modoboa never uses it for
#: accounts.
TOKEN_IDENTITY_PREFIX = ".modoboa-token-"

#: Share link tokens generated by Modoboa (hexadecimal)
SHARE_TOKEN_RE = re.compile(r"^[0-9a-f]{32,128}$")


def get_token_identity(token):
    """Return the user name of a share link token.

    The token is hashed: Radicale logs user names, and the hash can't
    be used to access the calendar.
    """
    return TOKEN_IDENTITY_PREFIX + hashlib.sha256(token.encode()).hexdigest()


def is_token_identity(login):
    """Check if login is a share link token and not an account."""
    return login.startswith(TOKEN_IDENTITY_PREFIX)


def redact_url(url):
    """Return url without the password it may contain, to log it."""
    parts = urlsplit(url)
    if parts.password is None:
        return url
    netloc = f"{parts.username}:***@{parts.hostname}"
    if parts.port:
        netloc += f":{parts.port}"
    return urlunsplit(parts._replace(netloc=netloc))


class Auth(DovecotAuth):
    """
    Custom authentication plugin using oAuth2 introspection mode.

    If the authentication fails with given credentials, it falls back to Dovecot
    authentication.

    When modoboa_rights_endpoint is set, requests with a ?token= query
    parameter (share links) are authenticated by asking the Modoboa API
    whether the token gives access to a calendar.

    Configuration:

    [auth]
    type = radicale_modoboa_auth_oauth2
    oauth2_introspection_endpoint = https://<modoboa>/api/o/introspect/
    # Credentials of Radicale's OAuth2 application. They can also be
    # given in the introspection URL (https://<id>:<secret>@...), but
    # separate settings keep the secret out of URLs.
    modoboa_client_id = <client id>
    modoboa_client_secret = <client secret>
    # Recommended: avoid one introspection call per CalDAV request
    cache_logins = True
    # Optional: share links
    modoboa_rights_endpoint = https://<modoboa>/api/v2/calendar-rights/
    # Optional, defaults to /api/o/token/ on the host of the rights endpoint
    modoboa_token_endpoint = https://<modoboa>/api/o/token/
    """

    def __init__(self, configuration):
        super().__init__(configuration)
        try:
            self._endpoint = configuration.get("auth", "oauth2_introspection_endpoint")
        except KeyError:
            raise RuntimeError("oauth2_introspection_endpoint must be set")
        logger.info(
            "Using oauth2 introspection endpoint: %s", redact_url(self._endpoint)
        )
        self._client_credentials = self._get_client_credentials(configuration)
        if self._client_credentials:
            # Client credentials are form-encoded before HTTP Basic
            # (RFC 6749, 2.3.1). They take precedence over the ones of
            # the URL.
            self._introspection_auth = tuple(map(quote_plus, self._client_credentials))
        else:
            # Credentials of the URL, if any, are used by requests
            self._introspection_auth = None
        # Keep the connection to the introspection endpoint alive
        self._session = requests.Session()
        self._rights_client = self._make_rights_client(configuration)
        self._enable_login_cache(configuration)

    @staticmethod
    def _get_option(configuration, name):
        try:
            return configuration.get("auth", name)
        except KeyError:
            return None

    def _get_client_credentials(self, configuration):
        """Return the client id and secret of Radicale's OAuth2 application.

        Return None when they are not set: both or none must be.
        """
        client_id = self._get_option(configuration, "modoboa_client_id")
        client_secret = self._get_option(configuration, "modoboa_client_secret")
        if not client_id and not client_secret:
            return None
        if not client_id or not client_secret:
            raise RuntimeError(
                "modoboa_client_id and modoboa_client_secret must be set together"
            )
        return client_id, client_secret

    def _make_rights_client(self, configuration):
        """Return the client used to check share link tokens, if enabled."""
        endpoint = self._get_option(configuration, "modoboa_rights_endpoint")
        if not endpoint:
            logger.info("Share links disabled: modoboa_rights_endpoint is not set")
            return None
        if not self._client_credentials:
            raise RuntimeError(
                "modoboa_client_id and modoboa_client_secret must be set "
                "with modoboa_rights_endpoint"
            )
        client = RightsClient(
            endpoint,
            *self._client_credentials,
            token_endpoint=self._get_option(configuration, "modoboa_token_endpoint"),
            timeout=SHARE_TOKEN_TIMEOUT,
        )
        logger.info(
            "Share links enabled, using Modoboa rights endpoint: %s "
            "(token endpoint: %s)",
            client.endpoint,
            client.token_endpoint,
        )
        return client

    def _enable_login_cache(self, configuration):
        """Enable Radicale's login cache for this plugin.

        Radicale only honors cache_logins for its builtin auth types, so it is
        always disabled for external plugins. Without it, every CalDAV request
        triggers an introspection call.
        """
        try:
            enabled = configuration.get("auth", "cache_logins")
        except KeyError:
            # Radicale version without login cache support
            return
        if not enabled or getattr(self, "_cache_logins", True) is True:
            return
        self._cache_logins = True
        self._cache_successful_logins_expiry = configuration.get(
            "auth", "cache_successful_logins_expiry"
        )
        self._cache_failed_logins_expiry = configuration.get(
            "auth", "cache_failed_logins_expiry"
        )
        self._cache_successful = dict()
        self._cache_failed = dict()
        self._cache_failed_logins_salt_ns = time.time_ns()
        logger.info(
            "auth.cache_logins enabled for oauth2 plugin (successful: %s sec, failed: %s sec)",
            self._cache_successful_logins_expiry,
            self._cache_failed_logins_expiry,
        )

    def _introspect(self, login, password):
        """Check if password is a valid access token for login."""
        headers = {"Content-Type": "application/x-www-form-urlencoded"}
        data = {
            "token": password
        }
        try:
            response = self._session.post(
                self._endpoint, data=data, headers=headers,
                auth=self._introspection_auth, timeout=INTROSPECTION_TIMEOUT
            )
        except requests.RequestException as exc:
            logger.error("OAuth2 introspection request failed: %s", exc)
            return False
        if response.status_code != 200:
            logger.warning(
                "OAuth2 introspection endpoint returned status %d",
                response.status_code
            )
            return False
        try:
            content = response.json()
        except ValueError:
            logger.error("OAuth2 introspection endpoint returned invalid JSON")
            return False
        return bool(content.get("active")) and content.get("username") == login

    def get_external_login(self, environ):
        """Authenticate share links with the token given in the query string.

        Other requests use HTTP authentication.
        """
        if self._rights_client is None:
            return ()
        tokens = parse_qs(environ.get("QUERY_STRING", "")).get("token")
        if not tokens or not SHARE_TOKEN_RE.match(tokens[0]):
            return ()
        # The token itself is the password: the identity alone, which
        # appears in logs, must not be enough to log in.
        return (get_token_identity(tokens[0]), tokens[0])

    def _check_share_token(self, identity, token):
        """Check if token matches identity and gives access to a calendar."""
        if self._rights_client is None:
            return False
        if not hmac.compare_digest(get_token_identity(token), identity):
            return False
        rights = self._rights_client.get_rights(identity)
        if rights is None:
            return False
        shares = rights.get("shares")
        return isinstance(shares, dict) and bool(shares)

    def _login_ext(self, login, password, context):
        if is_token_identity(login):
            # Never checked by introspection or Dovecot
            return login if self._check_share_token(login, password) else ""
        if self._introspect(login, password):
            return login
        return super()._login_ext(login, password, context)
